name: Deploy to GitHub Pages
on:
  push:
    branches:
      - prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: prod
    
    - name: Build
      run: |
        yarn install
        yarn run build
        cd dist
        echo 'bullinger.raphaelm.ch' > CNAME
        cd ..

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages-test
        FOLDER: dist